# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppompudata',
            name='title',
            field=models.CharField(default=22, max_length=100),
            preserve_default=False,
        ),
    ]
