# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_ppompudata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppompudata',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
