# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0005_categorydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydata',
            name='password',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
