# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0007_keyworddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyworddata',
            name='bulletinName',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
